In [1]:
# Import the required libraries and dependencies
import os
import requests
import json
import pandas as pd
from dotenv import load_dotenv
import alpaca_trade_api as tradeapi
from MCForecastTools import MCSimulation

%matplotlib inline

In [2]:
# Load the environment variables from the .env file
#by calling the load_dotenv function
load_dotenv()

True

In [3]:
# Set the variables for the Alpaca API and secret keys
# YOUR CODE HERE
# YOUR CODE HERE
import alpaca_trade_api as tradeapi

alpaca_api_key=os.getenv("ALPACA_API_KEY")
type(alpaca_api_key)

alpaca_secret_key = os.getenv("ALPACA_SECRET_KEY")
type(alpaca_secret_key)

# Create the Alpaca tradeapi.REST object
# YOUR CODE HERE
alpaca = tradeapi.REST(
    alpaca_api_key,
    alpaca_secret_key,
    api_version="v2")
alpaca


# btc eth usdt bnb usdc xrp ada steth hex doge matic sol
# jan 1 to 2013 jan 2023

In [4]:
# Set the tickers for both the bond and stock portion of the portfolio
# YOUR CODE HERE"
tickers = ["BTC", "ETH", "USDT","bnb", "usdc", "xrp", "ada", "steth", "hex", "doge", "matic", "sol"]

# Set timeframe to 1Day
# YOUR CODE HERE
timeframe = "1Day"

# Format current date as ISO format
# Set both the start and end date at the date of your prior weekday 
# This will give you the closing price of the previous trading day
# Alternatively you can use a start and end date of 2020-08-07
# YOUR CODE HERE
# YOUR CODE HERE
start_date = pd.Timestamp("2013-01-01", tz="America/New_York").isoformat()
end_date = pd.Timestamp("2023-01-01", tz="America/New_York").isoformat()

In [5]:
# Use the Alpaca get_bars function to get current closing prices the portfolio
# Be sure to set the `df` property after the function to format the response object as a DataFrame
# YOUR CODE HERE
df_portfolio = alpaca.get_bars(
    tickers,
    timeframe,
    start = start_date,
    end = end_date
).df

# Reorganize the DataFrame
# Separate ticker data
# YOUR CODE HERE
BTC = df_portfolio[df_portfolio['symbol']=='BTC'].drop('symbol', axis=1)
ETH = df_portfolio[df_portfolio['symbol']=='ETH'].drop('symbol', axis=1)
USDT = df_portfolio[df_portfolio['symbol']=='USDT'].drop('symbol', axis=1)
BNB = df_portfolio[df_portfolio['symbol']=='BNB'].drop('symbol', axis=1)
USDC = df_portfolio[df_portfolio['symbol']=='USDC'].drop('symbol', axis=1)
XRP = df_portfolio[df_portfolio['symbol']=='XRP'].drop('symbol', axis=1)
ADA = df_portfolio[df_portfolio['symbol']=='ADA'].drop('symbol', axis=1)
STETH = df_portfolio[df_portfolio['symbol']=='STETH'].drop('symbol', axis=1)
HEX = df_portfolio[df_portfolio['symbol']=='HEX'].drop('symbol', axis=1)
DOGE = df_portfolio[df_portfolio['symbol']=='DOGE'].drop('symbol', axis=1)
MATIC = df_portfolio[df_portfolio['symbol']=='MATIC'].drop('symbol', axis=1)
SOL = df_portfolio[df_portfolio['symbol']=='SOL'].drop('symbol', axis=1)


# Concatenate the ticker DataFrames
# YOUR CODE HERE
df_portfolio = pd.concat([BTC,ETH,USDT,BNB, USDC, XRP, ADA, STETH, HEX, DOGE, MATIC, SOL],axis=1, keys=["BTC","ETH","USDT","BNB","USDC","XRP","ADA","STETH","HEX","DOGE","MATIC","SOL"])

# Review the first 5 rows of the Alpaca DataFrame
# YOUR CODE HERE
df_portfolio.tail()

                           BTC                                         ETH  \
                          open high low close volume trade_count vwap open
timestamp
2022-12-23 05:00:00+00:00  NaN  NaN NaN   NaN    NaN         NaN  NaN  NaN
2022-12-27 05:00:00+00:00  NaN  NaN NaN   NaN    NaN         NaN  NaN  NaN
2022-12-28 05:00:00+00:00  NaN  NaN NaN   NaN    NaN         NaN  NaN  NaN
2022-12-29 05:00:00+00:00  NaN  NaN NaN   NaN    NaN         NaN  NaN  NaN
2022-12-30 05:00:00+00:00  NaN  NaN NaN   NaN    NaN         NaN  NaN  NaN

                                    ...  MATIC                    SOL         \
                          high low  ... volume trade_count vwap  open   high
timestamp                           ...
2022-12-23 05:00:00+00:00  NaN NaN  ...    NaN         NaN  NaN  4.32  4.415
2022-12-27 05:00:00+00:00  NaN NaN  ...    NaN         NaN  NaN  4.31  4.330
2022-12-28 05:00:00+00:00  NaN NaN  ...    NaN         NaN  NaN  4.15  4.195
2022-12-29 05:00:00+00:00  NaN NaN  ...    NaN         NaN  NaN  4.37  4.535
2022-12-30 05:00:00+00:00  NaN NaN  ...    NaN         NaN  NaN  4.41  4.580


                            low close  volume trade_count      vwap
timestamp
2022-12-23 05:00:00+00:00  4.13  4.38  665515        4098  4.335331
2022-12-27 05:00:00+00:00  4.18  4.19  553709        3342  4.230195
2022-12-28 05:00:00+00:00  4.05  4.17  535628        3585  4.134463
2022-12-29 05:00:00+00:00  4.30  4.52  846961        3586  4.475177
2022-12-30 05:00:00+00:00  4.41  4.52  497560        3338  4.510934

[5 rows x 84 columns]